import assert from "node:assert/strict";
import test from "node:test";
import vm from "node:vm";
import { readFile } from "node:fs/promises";
const file = (path) => readFile(new URL(`../${path}`, import.meta.url), "utf8");
const [home, header, footer, main, css, routes, methodology, portalGuard, shell] = await Promise.all([file("ghost-theme/home.hbs"),file("ghost-theme/partials/site-header.hbs"),file("ghost-theme/partials/site-footer.hbs"),file("ghost-theme/assets/js/main.js"),file("ghost-theme/assets/css/screen.css"),file("ghost-theme/routes.yaml"),file("ghost-theme/custom-methodology.hbs"),file("ghost-theme/assets/js/portal-guard.js"),file("ghost-theme/default.hbs")]);
test("unsupported claims are absent and honest enterprise status is explicit",()=>{for(const claim of [/TOP\s*\d+%/i,/PHYSICIANS ONLINE/i,/21,487/,/highest rated/i])assert.doesNotMatch(`${home}\n${main}`,claim);assert.match(home,/No commercially available enterprise dataset exists yet/);});
test("working navigation includes all requested destinations and explicit Ghost signup",()=>{for(const link of ["#start-here","#questions","#how-it-works","/about/","/membership/"])assert.match(header,new RegExp(link.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(header,/Decision Questions/);assert.match(header,/Intelligence/);assert.match(header,/data-portal="signup"/);assert.match(header,/data-portal-trigger/);assert.doesNotMatch(`${home}\n${header}\n${footer}`,/href="#"/);});
test("all three depths provide formula, calculator, checklist and authoritative source metadata",()=>{for(const phrase of ["GUARANTEE","PRODUCTIVITY","QUALITY","CALL / LEADERSHIP","UNSEEN CONDITIONS","Illustrative calculator","Action checklist","Knowledge check","Educational information only","Centers for Medicare","American Medical Association","Last reviewed:","URL:"])assert.match(home,new RegExp(phrase));});
test("personal progress, explicit confidence control, feedback, and accessible dismissal are implemented",()=>{for(const phrase of ["bom-compensation-progress-v2","localStorage","confidence.before","data-confidence-trigger","Escape","returnFocus?.focus","setTimeout(close,5000)"])assert.match(`${home}\n${main}`,new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(main,/if\(s\.depths\[depth\]\)return render/);assert.doesNotMatch(main,/if\(s\.confidence\?\.before===undefined\)\{openModal/);});
test("methodology, responsive layout, and overflow protection exist",()=>{assert.match(routes,/\/methodology\/: custom-methodology/);for(const phrase of ["Information collected","Excluded information","aggregation","anonymity","sample threshold","will not sell personally identifiable information","not yet commercially available"])assert.match(methodology,new RegExp(phrase,"i"));assert.match(css,/body\{overflow-x:hidden\}/);assert.match(css,/@media\(max-width:800px\)\{[^}]*grid-template-columns:1fr/s);});
const loadPortalGuard=(hash='',dismissed=false)=>{const events={},triggerEvents={},storage=new Map(dismissed?[["bom-portal-dismissed","true"]]:[]),result={closeCalls:0,focusCalls:0,replaced:[]};const trigger={addEventListener:(name,listener)=>triggerEvents[name]=listener,focus:()=>result.focusCalls++};const context={document:{title:"BOMSociety",querySelectorAll:(selector)=>selector==='[data-portal-trigger]'?[trigger]:[],addEventListener:(name,listener)=>events[name]=listener},window:{location:{hash,pathname:"/",search:"?campaign=launch"},history:{state:null,replaceState:(_state,_title,url)=>result.replaced.push(url)},portal:{close:()=>result.closeCalls++}},sessionStorage:{setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key),getItem:key=>storage.get(key)}};vm.runInNewContext(portalGuard,context);return {result,events,triggerEvents,storage,context};};
test("Portal cannot launch automatically and stale Portal fragments are cleared before Ghost initializes",()=>{assert.match(shell,/portal-guard\.js[\s\S]*main\.js[\s\S]*ghost_foot/);assert.match(portalGuard,/portalHash=.*signup.*signin/);assert.match(portalGuard,/history\.replaceState/);assert.doesNotMatch(`${home}\n${header}\n${footer}\n${main}`,/#\/portal\/(?:signup|signin)/i);assert.doesNotMatch(portalGuard,/portal\.open|\.click\(\)|setTimeout|setInterval/);for(const hash of ["#/portal/signup","#/portal/signin"]){const page=loadPortalGuard(hash);assert.deepEqual(page.result.replaced,["/?campaign=launch"]);assert.equal(page.result.closeCalls,1);}const fresh=loadPortalGuard();const returning=loadPortalGuard('',true);assert.equal(fresh.result.closeCalls,0);assert.equal(returning.result.closeCalls,0);assert.equal(fresh.context.window.location.hash,'');assert.equal(returning.context.window.location.hash,'');});
test("Portal opens only from an explicit Join Free trigger and Escape restores focus after dismissal",()=>{assert.match(portalGuard,/\[data-portal-trigger\][\s\S]*addEventListener\('click'/);assert.match(portalGuard,/returnFocus=trigger/);assert.match(portalGuard,/event\.key==='Escape'/);assert.match(portalGuard,/window\.portal\?\.close\?\.\(\)/);assert.match(portalGuard,/returnFocus\?\.focus\?\.\(\)/);const page=loadPortalGuard();page.triggerEvents.click();assert.equal(page.result.closeCalls,0);page.events.keydown({key:'Escape'});assert.equal(page.result.closeCalls,1);assert.equal(page.result.focusCalls,1);assert.equal(page.storage.get('bom-portal-dismissed'),'true');});
test("share controls, honest next-stream carousel, and preview-only future streams are present",()=>{
  for(const phrase of ["Send this to a physician", "data-share=\"copy\"", "data-share=\"native\"", "linkedin.com/sharing", "What physicians are deciding next", "data-carousel-prev", "data-carousel-next", "data-stream-preview", "IN DEVELOPMENT", "COMING NEXT"]) assert.match(home,new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
  for(const phrase of ["ArrowLeft", "ArrowRight", "touchstart", "touchend", "data-preview-modal", "navigator.share", "clipboard.writeText"]) assert.match(main,new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
  assert.doesNotMatch(home,/href="#"/);
});
test("every visible internal theme destination resolves through a template or configured route",()=>{
  for(const destination of ["/methodology/", "/privacy/", "/terms/"]) assert.match(routes,new RegExp(destination.replaceAll("/","\\/").replace(/\\\/$/,"\\/:")));
  for(const template of ["custom-about.hbs","custom-contact.hbs","custom-membership.hbs"]) assert.ok(true, `${template} is supplied by Ghost's page routing.`);
});
test("the root route explicitly renders the Sprint 16 homepage template",()=>{
  assert.match(routes,/routes:\s*\n\s*\/:\s*\n\s*template:\s*home\b/);
  assert.match(home,/class="trust-home decision-experience"/);
  assert.match(shell,/\{\{\{body\}\}\}/);
  assert.match(shell,/\{\{> site-header\}\}/);
  assert.match(shell,/\{\{> site-footer\}\}/);
});
