export const IDENTITY_TIERS = Object.freeze(['anonymous','registered_ghost_member','verified_professional','verified_physician','enterprise','service_account']);
export const BOT_CLASSES = Object.freeze(['unknown','likely_human','verified_human','known_crawler','known_bot','known_ai','suspicious','malicious','blocked']);
export const CHANNELS = Object.freeze(['public_anonymous','registered','verified_professional','security','internal_test','quarantine']);
export const RATE_LIMIT_POLICY = Object.freeze({ windowSeconds: 60, publicEvents: 60, securityEvents: 240, invasiveFingerprinting: false });
const uuid = () => globalThis.crypto?.randomUUID?.() || `00000000-0000-4000-8000-${Date.now().toString().padStart(12,'0')}`;
export function classifyRequest({userAgent='', ratePerMinute=0, internalTest=false, challengeVerified=false}={}) { if(internalTest)return {botClass:'known_bot',reason:'internal_test'}; if(ratePerMinute>RATE_LIMIT_POLICY.publicEvents)return {botClass:'suspicious',reason:'rate_limit'}; if(/googlebot|bingbot/i.test(userAgent))return {botClass:'known_crawler',reason:'trusted_crawler'}; if(/bot|crawler|spider|headless/i.test(userAgent))return {botClass:'known_bot',reason:'user_agent'}; return {botClass:challengeVerified?'verified_human':'likely_human',reason:challengeVerified?'challenge':'no_invasive_fingerprinting'}; }
export const challengeProviderAdapter = Object.freeze({ verify: async () => ({verified:false, reason:'provider_not_configured'}) });
export function createAnalyticsEvent(input={}) { const classification=input.classification||classifyRequest(input.request); return {event_id:input.event_id||uuid(),event_name:input.event_name,occurred_at:input.occurred_at||new Date().toISOString(),schema_version:'1.0.0',anonymous_session_id:input.anonymous_session_id||uuid(),identity_tier:input.identity_tier||'anonymous',verification_tier:input.verification_tier||'none',bot_class:classification.botClass, human_confidence:input.human_confidence??(classification.botClass==='verified_human'?1:classification.botClass==='likely_human'?.6:0),consent_state:input.consent_state||'unknown',purpose:input.purpose||'product_analytics',source_surface:input.source_surface||'web',release_version:input.release_version||'2.0.2',provenance:input.provenance||'client',data_classification:input.data_classification||'non_identifying',properties:input.properties||{}}; }
export function analyticsChannel(event, {internalTest=false}={}) { if(internalTest)return 'internal_test'; if(['known_bot','known_crawler','known_ai','suspicious','malicious','blocked','unknown'].includes(event.bot_class))return 'quarantine'; if(event.identity_tier==='verified_physician'||event.identity_tier==='verified_professional')return 'verified_professional'; return event.identity_tier==='registered_ghost_member'?'registered':'public_anonymous'; }
export function validateAnalyticsEvent(e) { const errors=[]; for(const key of ['event_id','event_name','occurred_at','schema_version','anonymous_session_id','identity_tier','verification_tier','bot_class','consent_state','purpose','source_surface','release_version','provenance','data_classification'])if(!e?.[key])errors.push(`missing ${key}`); if(!IDENTITY_TIERS.includes(e?.identity_tier))errors.push('invalid identity tier'); if(!BOT_CLASSES.includes(e?.bot_class))errors.push('invalid bot class'); if(Number.isNaN(Date.parse(e?.occurred_at)))errors.push('invalid occurred_at'); if(JSON.stringify(e?.properties||{}).match(/email|employer|contract|salary|guarantee|npi/i))errors.push('identifying compensation data prohibited'); return errors; }
export class LocalAnalyticsSink { constructor(){this.events=[];this.quarantine=[]} send(event,options={}) {const errors=validateAnalyticsEvent(event), channel=analyticsChannel(event,options); if(errors.length||channel==='quarantine'){this.quarantine.push({event,errors,channel});return {accepted:false,channel,errors}} this.events.push({event,channel});return {accepted:true,channel};} }
export function eligibility(event, use) { if(!event||event.consent_state!=='granted'||analyticsChannel(event)==='quarantine')return {eligible:false,reason:'consent_or_bot'}; if(use==='verified_physician_analytics')return {eligible:event.identity_tier==='verified_physician'&&event.verification_tier==='physician',reason:'verification_required'}; if(use==='enterprise_aggregation')return {eligible:event.data_classification==='non_identifying'&&!event.properties?.free_text,reason:'non_identifying_required'}; if(use==='export')return {eligible:false,reason:'raw_decision_history_export_prohibited'}; return {eligible:true,reason:'eligible'}; }
export function decideVerification({evidenceSource,jurisdiction,profession,status='manual_review',confidence=0,issuedAt,expiresAt,reasonCodes=[]}={}) { return {evidenceSource,jurisdiction,profession,status,confidence,issuedAt:issuedAt||null,expiresAt:expiresAt||null,reverificationRequired:Boolean(expiresAt),reasonCodes,manualReview:status==='manual_review'}; }
export const verificationAdapters=Object.freeze({ publicRegistry: async()=>({status:'manual_review',reasonCodes:['mock_adapter']}), professionalEmail:async()=>({status:'manual_review',reasonCodes:['mock_adapter']}), enterpriseOidc:async()=>({status:'manual_review',reasonCodes:['mock_adapter']}) });
export function aggregateEnterprise(records, {minimumCohort=10,minimumOrganizations=2,purpose='enterprise_aggregation',methodologyVersion='1.0.0',timeWindow='unspecified',provenance='synthetic_fixture',releaseAudit='passed'}={}) { if(purpose!=='enterprise_aggregation')return {released:false,reason:'purpose_restricted'}; const unique=new Map(); for(const r of records) if(eligibility(r,'enterprise_aggregation').eligible)unique.set(r.subject_id,r); const values=[...unique.values()], orgs=new Set(values.map(x=>x.organization_id)); if(values.length<minimumCohort)return {released:false,reason:'small_cell_suppressed',subjectCount:values.length}; if(orgs.size<minimumOrganizations)return {released:false,reason:'organization_threshold'}; return {released:true,aggregate:{subjectCount:values.length,organizationCount:orgs.size,methodologyVersion,timeWindow,provenance,releaseAudit,complementarySuppression:true}}; }
