import test from "node:test";
import assert from "node:assert/strict";
import { createAnonymousIdentity, createVerifiedMemberRecord, analyticsActor, ConsentAwarePipeline, MemoryEventTransport, validateEvent, aggregateDaily, aggregateWeekly, aggregateMonthly, createEnterpriseIntelligenceRecord, classifyBot } from "../src/index.js";
const storage = () => { const data = new Map(); return { getItem: k => data.get(k) || null, setItem: (k,v) => data.set(k,v) }; };
test("pipeline creates UUID-traceable, versioned first-party events", async () => { const transport = new MemoryEventTransport(); const identity = createAnonymousIdentity(storage()); const pipeline = new ConsentAwarePipeline({ transport, identity, consent: () => "granted" }); const result = await pipeline.track("page_view", {}, { path: "/briefs" }); assert.equal(result.accepted, true); assert.equal(transport.events.length, 1); assert.deepEqual(validateEvent(result.event), []); assert.equal(result.event.schemaVersion, 1); });
test("pipeline blocks denied consent and bot traffic before transport", async () => { const transport = new MemoryEventTransport(); const identity = createAnonymousIdentity(storage()); const denied = new ConsentAwarePipeline({ transport, identity, consent: () => "denied" }); assert.equal((await denied.track("page_view", {}, { path: "/" })).reason, "consent"); const bot = new ConsentAwarePipeline({ transport, identity, consent: () => "granted", botContext: () => ({ userAgent: "Googlebot" }) }); assert.equal((await bot.track("page_view", {}, { path: "/" })).reason, "bot"); assert.equal(transport.events.length, 0); });
test("identity records are separate and member IDs are prohibited from events", () => { const identity = createAnonymousIdentity(storage()); const member = createVerifiedMemberRecord({ memberId: "member-42", verificationMethod: "email-link" }); assert.equal(member.memberId, "member-42"); assert.equal(analyticsActor(identity, true).memberId, undefined); const event = { schemaVersion: 1,eventId:crypto.randomUUID(),type:"page_view",version:1,occurredAt:new Date().toISOString(),trace:{traceId:crypto.randomUUID(),sessionId:identity.sessionId},actor:{...analyticsActor(identity),memberId:"member-42"},consent:"granted",context:{path:"/"},properties:{} }; assert.match(validateEvent(event).join(" "), /memberId/); });
test("enterprise model suppresses small cohorts and bot framework returns evidence", () => { assert.throws(() => createEnterpriseIntelligenceRecord({ period:"2026-07",topic:"contracts",cohortSize:9,searches:1,completions:1,decisionPaths:1 }), /at least 10/); assert.deepEqual(classifyBot({ userAgent: "Mozilla", ratePerMinute: 121 }), { isBot: true, reasons: ["rate_limit_exceeded"] }); });
test("daily, weekly, and monthly aggregations deduplicate sessions", () => { const s = crypto.randomUUID(); const events = [0, 1].map(i => ({ occurredAt:`2026-07-2${i}T12:00:00.000Z`, type:"page_view", trace:{sessionId:s} })); assert.equal(aggregateDaily(events)[0].sessions, 1); assert.equal(aggregateWeekly(events)[0].events, 2); assert.equal(aggregateMonthly(events)[0].sessions, 1); });
