routes:
  /:
    template: home
  /methodology/: custom-methodology
  /privacy/: custom-privacy
  /terms/: custom-terms
collections:
  /briefs/:
    permalink: /briefs/{slug}/
    template: index
taxonomies:
  tag: /topic/{slug}/
  author: /author/{slug}/
